/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/knowgrph-mcp/wrangler.toml --include-runtime=false cloudflare/workers/knowgrph-mcp/worker-configuration.d.ts` (hash: cc4ba9de16a98c2764368cde3673c23d)
interface __BaseEnv_Env {
	TRAVEL_AGENT_DEFINITION_CACHE: KVNamespace;
	AI: Ai;
	KNOWGRPH_MCP_PUBLIC_BASE_URL: "https://knowgrph-mcp-staging.huijoohwee.workers.dev" | "https://knowgrph-mcp-dev.huijoohwee.workers.dev" | "https://airvio.co";
	KNOWGRPH_MCP_TOOL_LIST_NAME: "knowgrph-video-remix-staging" | "knowgrph-video-remix-dev" | "knowgrph-video-remix";
	KNOWGRPH_LIVE_CLIENTS: "0";
	TRAVEL_AGENT_DEFINITIONS_JSON: "[{\"agentId\":\"agent-flight\",\"declaredCategory\":\"flight\"},{\"agentId\":\"agent-experience\",\"declaredCategory\":\"experience\"}]" | "[{\"agentId\":\"agent-flight\",\"declaredCategory\":\"flight\"},{\"agentId\":\"agent-hotel\",\"declaredCategory\":\"hotel\"},{\"agentId\":\"agent-experience\",\"declaredCategory\":\"experience\"}]";
	TRAVEL_DISCOVERY_MODE: "live" | "deterministic-demo";
	TRAVEL_DISCOVERY_DEADLINE_MS: "6000";
	TRAVEL_SETTLEMENT_CURRENCY: "SGD";
	MCP_AGENT: DurableObjectNamespace<import("./index").KnowgrphMcpAgent>;
	RUN_MANIFEST_STORE: DurableObjectNamespace<import("./index").RunManifestStore>;
	TRAVEL_DISCOVERY_HARNESS: Fetcher /* knowgrph-travel-discovery-staging */ | Fetcher /* knowgrph-travel-discovery */;
	TRAVEL_EXPERIENCE_DISCOVERY_HARNESS?: Fetcher /* knowgrph-travel-experience-discovery-staging */ | Fetcher /* knowgrph-travel-experience-discovery-production */;
	TRAVEL_DEMO_QUOTE_RULES_JSON?: "{\"flight\":{\"deltaMinor\":50},\"hotel\":{\"deltaMinor\":25},\"experience\":{\"deltaMinor\":10}}";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "KnowgrphMcpAgent" | "RunManifestStore";
	}
	interface StagingEnv {
		TRAVEL_AGENT_DEFINITION_CACHE: KVNamespace;
		AI: Ai;
		KNOWGRPH_MCP_PUBLIC_BASE_URL: "https://knowgrph-mcp-staging.huijoohwee.workers.dev";
		KNOWGRPH_MCP_TOOL_LIST_NAME: "knowgrph-video-remix-staging";
		KNOWGRPH_LIVE_CLIENTS: "0";
		TRAVEL_AGENT_DEFINITIONS_JSON: "[{\"agentId\":\"agent-flight\",\"declaredCategory\":\"flight\"},{\"agentId\":\"agent-experience\",\"declaredCategory\":\"experience\"}]";
		TRAVEL_DISCOVERY_MODE: "live";
		TRAVEL_DISCOVERY_DEADLINE_MS: "6000";
		TRAVEL_SETTLEMENT_CURRENCY: "SGD";
		MCP_AGENT: DurableObjectNamespace<import("./index").KnowgrphMcpAgent>;
		RUN_MANIFEST_STORE: DurableObjectNamespace<import("./index").RunManifestStore>;
		TRAVEL_DISCOVERY_HARNESS: Fetcher /* knowgrph-travel-discovery-staging */;
		TRAVEL_EXPERIENCE_DISCOVERY_HARNESS: Fetcher /* knowgrph-travel-experience-discovery-staging */;
	}
	interface DevEnv {
		TRAVEL_AGENT_DEFINITION_CACHE: KVNamespace;
		AI: Ai;
		KNOWGRPH_MCP_PUBLIC_BASE_URL: "https://knowgrph-mcp-dev.huijoohwee.workers.dev";
		KNOWGRPH_MCP_TOOL_LIST_NAME: "knowgrph-video-remix-dev";
		KNOWGRPH_LIVE_CLIENTS: "0";
		TRAVEL_AGENT_DEFINITIONS_JSON: "[{\"agentId\":\"agent-flight\",\"declaredCategory\":\"flight\"},{\"agentId\":\"agent-hotel\",\"declaredCategory\":\"hotel\"},{\"agentId\":\"agent-experience\",\"declaredCategory\":\"experience\"}]";
		TRAVEL_DISCOVERY_MODE: "deterministic-demo";
		TRAVEL_DISCOVERY_DEADLINE_MS: "6000";
		TRAVEL_SETTLEMENT_CURRENCY: "SGD";
		TRAVEL_DEMO_QUOTE_RULES_JSON: "{\"flight\":{\"deltaMinor\":50},\"hotel\":{\"deltaMinor\":25},\"experience\":{\"deltaMinor\":10}}";
		MCP_AGENT: DurableObjectNamespace<import("./index").KnowgrphMcpAgent>;
		RUN_MANIFEST_STORE: DurableObjectNamespace<import("./index").RunManifestStore>;
		TRAVEL_DISCOVERY_HARNESS: Fetcher /* knowgrph-travel-discovery-staging */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "KNOWGRPH_MCP_PUBLIC_BASE_URL" | "KNOWGRPH_MCP_TOOL_LIST_NAME" | "KNOWGRPH_LIVE_CLIENTS" | "TRAVEL_AGENT_DEFINITIONS_JSON" | "TRAVEL_DISCOVERY_MODE" | "TRAVEL_DISCOVERY_DEADLINE_MS" | "TRAVEL_SETTLEMENT_CURRENCY" | "TRAVEL_DEMO_QUOTE_RULES_JSON">> {}
}
