/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/knowgrph-travel-commerce/wrangler.jsonc --include-runtime=false --env-interface=TravelCommerceEnv cloudflare/workers/knowgrph-travel-commerce/worker-configuration.d.ts` (hash: fdf7bc782793036e5a3d440fd3f00944)
interface __BaseEnv_TravelCommerceEnv {
	BALANCE_CACHE: KVNamespace;
	PROVENANCE_ARCHIVE: R2Bucket;
	DEPLOY_LANE: "Dev_Lane";
	CASCADE_WALL_MS: "10000";
	SETTLEMENT_CURRENCY: "SGD";
	MODEL_CATALOG_JSON: "[]";
	PERMITTED_MODEL_LICENSES_JSON: "[\"Apache-2.0\",\"MIT\"]";
	BUNDLE_GRAPH: DurableObjectNamespace<import("./src/index").BundleGraphStore>;
	ENVELOPE_LEDGER: DurableObjectNamespace<import("./src/index").EnvelopeLedger>;
	DISCOVERY_SERVICE: Fetcher /* knowgrph-mcp */;
	ISSUANCE_SERVICE: Fetcher /* knowgrph-payment */;
	INFERENCE_PRIMARY: Fetcher /* knowgrph-travel-workers-ai */;
	INFERENCE_OVERFLOW: Fetcher /* knowgrph-travel-ollama-overflow */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BundleGraphStore" | "EnvelopeLedger";
	}
	interface Env extends __BaseEnv_TravelCommerceEnv {}
}
interface TravelCommerceEnv extends __BaseEnv_TravelCommerceEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOY_LANE" | "CASCADE_WALL_MS" | "SETTLEMENT_CURRENCY" | "MODEL_CATALOG_JSON" | "PERMITTED_MODEL_LICENSES_JSON">> {}
}
