/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/knowgrph-travel-commerce/wrangler.jsonc --include-runtime=false --env-interface=TravelCommerceEnv cloudflare/workers/knowgrph-travel-commerce/worker-configuration.d.ts` (hash: 486f2b72549eb9b665419b0c265be1be)
interface __BaseEnv_TravelCommerceEnv {
	BALANCE_CACHE: KVNamespace;
	PROVENANCE_ARCHIVE: R2Bucket;
	AI: Ai;
	DEPLOY_LANE: "Staging_Lane" | "Production_Lane" | "Dev_Lane";
	CASCADE_WALL_MS: "10000";
	SETTLEMENT_CURRENCY: "SGD";
	MODEL_CATALOG_JSON: "[{\"id\":\"@cf/openai/gpt-oss-20b\",\"license\":\"Apache-2.0\",\"path\":\"workers-ai\",\"input_usd_per_million\":0.2,\"output_usd_per_million\":0.3},{\"id\":\"qwen3:0.6b\",\"license\":\"Apache-2.0\",\"path\":\"containers-ollama\",\"estimated_usd_per_call\":0.000205}]";
	PERMITTED_MODEL_LICENSES_JSON: "[\"Apache-2.0\",\"MIT\"]";
	BUNDLE_GRAPH: DurableObjectNamespace<import("./src/index").BundleGraphStore>;
	ENVELOPE_LEDGER: DurableObjectNamespace<import("./src/index").EnvelopeLedger>;
	DISCOVERY_SERVICE: Fetcher /* knowgrph-mcp-staging */ | Fetcher /* knowgrph-mcp */ | Fetcher /* knowgrph-mcp-dev */;
	ISSUANCE_SERVICE: Fetcher /* knowgrph-travel-net-settlement-staging */ | Fetcher /* knowgrph-travel-net-settlement-production */ | Fetcher /* knowgrph-travel-net-settlement-dev */;
	INFERENCE_OVERFLOW: Fetcher /* knowgrph-travel-ollama-overflow-staging */ | Fetcher /* knowgrph-travel-ollama-overflow */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BundleGraphStore" | "EnvelopeLedger";
	}
	interface StagingEnv {
		BALANCE_CACHE: KVNamespace;
		PROVENANCE_ARCHIVE: R2Bucket;
		AI: Ai;
		DEPLOY_LANE: "Staging_Lane";
		CASCADE_WALL_MS: "10000";
		SETTLEMENT_CURRENCY: "SGD";
		MODEL_CATALOG_JSON: "[{\"id\":\"@cf/openai/gpt-oss-20b\",\"license\":\"Apache-2.0\",\"path\":\"workers-ai\",\"input_usd_per_million\":0.2,\"output_usd_per_million\":0.3},{\"id\":\"qwen3:0.6b\",\"license\":\"Apache-2.0\",\"path\":\"containers-ollama\",\"estimated_usd_per_call\":0.000205}]";
		PERMITTED_MODEL_LICENSES_JSON: "[\"Apache-2.0\",\"MIT\"]";
		BUNDLE_GRAPH: DurableObjectNamespace<import("./src/index").BundleGraphStore>;
		ENVELOPE_LEDGER: DurableObjectNamespace<import("./src/index").EnvelopeLedger>;
		DISCOVERY_SERVICE: Fetcher /* knowgrph-mcp-staging */;
		ISSUANCE_SERVICE: Fetcher /* knowgrph-travel-net-settlement-staging */;
		INFERENCE_OVERFLOW: Fetcher /* knowgrph-travel-ollama-overflow-staging */;
	}
	interface ProductionEnv {
		BALANCE_CACHE: KVNamespace;
		PROVENANCE_ARCHIVE: R2Bucket;
		AI: Ai;
		DEPLOY_LANE: "Production_Lane";
		CASCADE_WALL_MS: "10000";
		SETTLEMENT_CURRENCY: "SGD";
		MODEL_CATALOG_JSON: "[{\"id\":\"@cf/openai/gpt-oss-20b\",\"license\":\"Apache-2.0\",\"path\":\"workers-ai\",\"input_usd_per_million\":0.2,\"output_usd_per_million\":0.3},{\"id\":\"qwen3:0.6b\",\"license\":\"Apache-2.0\",\"path\":\"containers-ollama\",\"estimated_usd_per_call\":0.000205}]";
		PERMITTED_MODEL_LICENSES_JSON: "[\"Apache-2.0\",\"MIT\"]";
		BUNDLE_GRAPH: DurableObjectNamespace<import("./src/index").BundleGraphStore>;
		ENVELOPE_LEDGER: DurableObjectNamespace<import("./src/index").EnvelopeLedger>;
		DISCOVERY_SERVICE: Fetcher /* knowgrph-mcp */;
		ISSUANCE_SERVICE: Fetcher /* knowgrph-travel-net-settlement-production */;
		INFERENCE_OVERFLOW: Fetcher /* knowgrph-travel-ollama-overflow */;
	}
	interface Env extends __BaseEnv_TravelCommerceEnv {}
}
interface TravelCommerceEnv extends __BaseEnv_TravelCommerceEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOY_LANE" | "CASCADE_WALL_MS" | "SETTLEMENT_CURRENCY" | "MODEL_CATALOG_JSON" | "PERMITTED_MODEL_LICENSES_JSON">> {}
}
