/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/agenticgraph-travel-experience-discovery/wrangler.jsonc --include-runtime=false --env-interface=ExperienceDiscoveryEnv cloudflare/workers/agenticgraph-travel-experience-discovery/worker-configuration.d.ts` (hash: 64fdd248a5a9dbf727c38b56fbafe8ba)
interface __BaseEnv_ExperienceDiscoveryEnv {
	EXPERIENCE_ENVIRONMENT: "staging" | "production" | "development";
	EXPERIENCE_AGENT_ID: "agent-experience";
	EXPERIENCE_PROVIDER_ID: "unconfigured";
	EXPERIENCE_PROVIDER_BASE_URL: "https://experience-provider-staging.invalid" | "https://experience-provider-production.invalid" | "https://experience-provider-dev.invalid";
	EXPERIENCE_PROVIDER_SEARCH_PATH: "/v1/experiences/search";
	EXPERIENCE_PROVIDER_VERIFY_PATH: "/v1/experiences/verify";
	EXPERIENCE_ROUTE_CATALOGUE_JSON: "{}";
	EXPERIENCE_PROVIDER_TIMEOUT_MS: "5500";
	EXPERIENCE_READINESS_TIMEOUT_MS: "5500";
	EXPERIENCE_MAX_RESPONSE_BYTES: "1048576";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface StagingEnv {
		EXPERIENCE_ENVIRONMENT: "staging";
		EXPERIENCE_AGENT_ID: "agent-experience";
		EXPERIENCE_PROVIDER_ID: "unconfigured";
		EXPERIENCE_PROVIDER_BASE_URL: "https://experience-provider-staging.invalid";
		EXPERIENCE_PROVIDER_SEARCH_PATH: "/v1/experiences/search";
		EXPERIENCE_PROVIDER_VERIFY_PATH: "/v1/experiences/verify";
		EXPERIENCE_ROUTE_CATALOGUE_JSON: "{}";
		EXPERIENCE_PROVIDER_TIMEOUT_MS: "5500";
		EXPERIENCE_READINESS_TIMEOUT_MS: "5500";
		EXPERIENCE_MAX_RESPONSE_BYTES: "1048576";
	}
	interface ProductionEnv {
		EXPERIENCE_ENVIRONMENT: "production";
		EXPERIENCE_AGENT_ID: "agent-experience";
		EXPERIENCE_PROVIDER_ID: "unconfigured";
		EXPERIENCE_PROVIDER_BASE_URL: "https://experience-provider-production.invalid";
		EXPERIENCE_PROVIDER_SEARCH_PATH: "/v1/experiences/search";
		EXPERIENCE_PROVIDER_VERIFY_PATH: "/v1/experiences/verify";
		EXPERIENCE_ROUTE_CATALOGUE_JSON: "{}";
		EXPERIENCE_PROVIDER_TIMEOUT_MS: "5500";
		EXPERIENCE_READINESS_TIMEOUT_MS: "5500";
		EXPERIENCE_MAX_RESPONSE_BYTES: "1048576";
	}
	interface Env extends __BaseEnv_ExperienceDiscoveryEnv {}
}
interface ExperienceDiscoveryEnv extends __BaseEnv_ExperienceDiscoveryEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "EXPERIENCE_ENVIRONMENT" | "EXPERIENCE_AGENT_ID" | "EXPERIENCE_PROVIDER_ID" | "EXPERIENCE_PROVIDER_BASE_URL" | "EXPERIENCE_PROVIDER_SEARCH_PATH" | "EXPERIENCE_PROVIDER_VERIFY_PATH" | "EXPERIENCE_ROUTE_CATALOGUE_JSON" | "EXPERIENCE_PROVIDER_TIMEOUT_MS" | "EXPERIENCE_READINESS_TIMEOUT_MS" | "EXPERIENCE_MAX_RESPONSE_BYTES">> {}
}
