/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/agentic-graph-storage/wrangler.toml --include-runtime=false --env-interface=AgenticGraphStorageBindings cloudflare/workers/agentic-graph-storage/worker-configuration.d.ts` (hash: f6bf124333c0d0bed608338640ecb37e)
interface __BaseEnv_AgenticGraphStorageBindings {
	AGENTIC_OS_STORAGE_BLOB_BUCKET: R2Bucket;
	DB: D1Database;
	SHARED_NODE_MAX_DELTA_BYTES: "65536";
	SHARED_NODE_MAX_PAYLOAD_BYTES: "262144";
	SHARED_NODE_REPLAY_LOG_MAX_ENTRIES: "128";
	SHARED_NODE_TRAVEL_DISPATCH_TIMEOUT_MS: "12000";
	AGENTIC_OS_STORAGE_LOCAL_RUNTIME: "false";
	AGENTIC_OS_CANVAS_ROOM: DurableObjectNamespace<import("./index").AgenticGraphCanvasSyncRoom>;
	AGENTIC_OS_TRAVEL_COMMERCE: Fetcher /* agentic-travel-commerce-production */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "AgenticGraphCanvasSyncRoom";
	}
	interface Env extends __BaseEnv_AgenticGraphStorageBindings {}
}
interface AgenticGraphStorageBindings extends __BaseEnv_AgenticGraphStorageBindings {}
