import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import test from 'node:test'
import fc from 'fast-check'

import { generateDiscoverySurfaces } from '../discovery-generate.mjs'
import { assembleCatalog } from '../invocation-assemble.mjs'
import {
  appendPromotionRecord,
  validateOperatorInstruction,
  validatePromotionRecord,
} from '../ledger.mjs'
import { evaluatePublicationGate } from '../publication-gate.mjs'
import { scanCandidate } from '../secret-scan.mjs'

const PROPERTY_RUNS = 100
const FIXED_NOW = '2026-07-27T00:00:02.000Z'
const EMPTY_CATALOG_DIGEST = '37517e5f3dc66819f61f5a7bb8ace1921282415f10551d2defa5c3eb0985b570'

const categoryCases = {
  'credential-material': index => `provider=sk-${String(index).padStart(36, 'a')}`,
  'signed-url': index => (
    `url=https://public.example/object?X-Amz-Signature=${String(index).padStart(32, 'a')}`
  ),
  'private-host': index => `endpoint=http://10.20.30.${1 + (index % 200)}/v1`,
  'local-absolute-path': index => `config=/Users/property-${index}/private/config.json`,
}

const candidateArbitrary = fc.array(
  fc.constantFrom(...Object.keys(categoryCases)),
  { minLength: 1, maxLength: 40 },
)

// Feature: discoverability-ip-protection, Property 10: Secret scan coverage is complete or blocking.
test('Property 10: every randomized candidate is scanned across planted categories and shortfalls block', () => {
  fc.assert(fc.property(candidateArbitrary, fc.nat(), (categories, seed) => {
    const candidates = categories.map((category, index) => ({
      path: `candidate-${index}.txt`,
      content: categoryCases[category](index),
    }))
    const complete = scanCandidate(candidates, {
      now: () => FIXED_NOW,
      monotonicNow: () => 0,
    })
    assert.equal(complete.complete, true)
    assert.equal(complete.scannedCount, candidates.length)
    assert.equal(complete.timestamp, FIXED_NOW)
    for (let index = 0; index < candidates.length; index += 1) {
      assert.equal(
        complete.matches.some(match => (
          match.path === candidates[index].path
          && match.category === categories[index]
        )),
        true,
      )
    }

    const missingIndex = seed % candidates.length
    const incompleteCandidates = candidates.map((candidate, index) => (
      index === missingIndex ? { ...candidate, content: null } : candidate
    ))
    const incomplete = scanCandidate(incompleteCandidates, {
      now: () => FIXED_NOW,
      monotonicNow: () => 0,
    })
    assert.equal(incomplete.complete, false)
    assert.equal(incomplete.scannedCount, candidates.length - 1)

    const gate = evaluatePublicationGate({
      registry: { entries: [] },
      candidatePaths: candidates.map(candidate => candidate.path),
      candidateFiles: incompleteCandidates,
      classification: {
        resolved: candidates.map(candidate => ({
          path: candidate.path,
          tier: 'public-artifact',
        })),
        unclassified: [],
      },
      scanResult: incomplete,
    })
    assert.equal(gate.decision, 'block')
    assert.equal(gate.blocks.some(block => block.code === 'FC-SCAN-INCOMPLETE'), true)
  }), { numRuns: PROPERTY_RUNS })
})

const safeWindowsAbsent = (serialized, value) => {
  for (let index = 0; index <= value.length - 8; index += 1) {
    assert.equal(serialized.includes(value.slice(index, index + 8)), false)
  }
}

// Feature: discoverability-ip-protection, Property 11: Secrets and runtime endpoints are redacted.
test('Property 11: randomized detected values never leak through scan, gate, or generated bytes', () => {
  fc.assert(fc.property(
    fc.stringMatching(/^[A-Za-z0-9_-]{20,60}$/u),
    (suffix) => {
      const secret = `sk-${suffix}`
      const endpointLabel = `runtime-${suffix}.private.example`
      const candidate = { path: 'candidate.txt', content: `token=${secret}` }
      const scanResult = scanCandidate([candidate], {
        now: () => FIXED_NOW,
        monotonicNow: () => 0,
      })
      const gate = evaluatePublicationGate({
        registry: { entries: [] },
        candidatePaths: [candidate.path],
        classification: {
          resolved: [{ path: candidate.path, tier: 'public-artifact' }],
          unclassified: [],
        },
        scanResult,
      })
      safeWindowsAbsent(JSON.stringify(scanResult), secret)
      safeWindowsAbsent(JSON.stringify(gate), secret)

      const generated = generateDiscoverySurfaces({
        publicOrigin: 'https://airvio.co',
        version: '1.0.0',
        catalogDigest: EMPTY_CATALOG_DIGEST,
        invocationRegistry: { catalogId: 'empty', entries: [] },
        entries: [{
          artifactId: 'protected-runtime',
          path: 'src/runtime.mjs',
          surfaceTier: 'private',
          artifactClass: 'runtime-config',
          licenseId: 'NONE-private',
          notes: `https://${endpointLabel}/invoke`,
        }],
      })
      const output = Buffer.concat([...generated.files.values()]).toString('utf8')
      assert.equal(output.includes(endpointLabel), false)
    },
  ), { numRuns: PROPERTY_RUNS })
})

const invocationCase = fc.constantFrom(
  'public-read',
  'public-write',
  'spend-wrong-route',
  'hosted-action',
  'hosted-direct-endpoint',
)

const invocationFor = (kind, index) => {
  const token = kind.startsWith('hosted-') ? `/action-${index}` : `tool_${index}`
  const common = {
    token,
    prefixRole: kind.startsWith('hosted-') ? 'action' : 'mcp-tool-id',
    label: `Capability ${index}`,
    intentSummary: `Capability metadata number ${index}.`,
    executionRouteTier: kind === 'public-read' || kind === 'public-write'
      ? 'public-discoverable'
      : 'gated',
    spendBearing: kind === 'spend-wrong-route',
    readOnly: kind === 'public-read',
  }
  if (kind.startsWith('hosted-')) {
    return {
      ...common,
      ingressRoute: 'invocation-forwarder',
      targetExecutionRoute: 'control-plane-mcp',
      ...(kind === 'hosted-direct-endpoint'
        ? { endpoint: `https://direct-${index}.example/invoke` }
        : {}),
    }
  }
  return {
    ...common,
    ingressRoute: 'public-read-mcp',
    targetExecutionRoute: kind === 'spend-wrong-route'
      ? 'public-read-mcp'
      : 'public-read-mcp',
  }
}

// Feature: discoverability-ip-protection, Property 12: Public tools are read-only and spend routes are gated.
test('Property 12: randomized invocation sets publish only read-only tools and reject unsafe routes', () => {
  fc.assert(fc.property(
    fc.array(invocationCase, { minLength: 1, maxLength: 30 }),
    kinds => {
      const rawEntries = kinds.map(invocationFor)
      const catalog = assembleCatalog([{ catalogId: 'property', entries: rawEntries }])
      const retained = new Set(catalog.entries.map(entry => entry.token))
      kinds.forEach((kind, index) => {
        const token = rawEntries[index].token
        if (kind === 'spend-wrong-route' || kind === 'hosted-direct-endpoint') {
          assert.equal(retained.has(token), false)
        }
        if (kind === 'hosted-action') {
          const entry = catalog.entries.find(candidate => candidate.token === token)
          assert.equal(entry.ingressRoute, 'invocation-forwarder')
          assert.equal(entry.targetExecutionRoute, 'control-plane-mcp')
          assert.equal(JSON.stringify(entry).includes('https://'), false)
        }
      })

      const generated = generateDiscoverySurfaces({
        publicOrigin: 'https://airvio.co',
        version: '1.0.0',
        catalogDigest: catalog.digest,
        invocationRegistry: { catalogId: 'property', entries: rawEntries },
        entries: [],
      })
      const manifest = JSON.parse(generated.files.get('.well-known/mcp.json'))
      const expectedTools = catalog.entries
        .filter(entry => (
          entry.prefixRole === 'mcp-tool-id'
          && entry.executionRouteTier === 'public-discoverable'
          && entry.readOnly
        ))
        .map(entry => entry.token)
        .sort()
      assert.deepEqual(manifest.capabilities.tools.map(tool => tool.name).sort(), expectedTools)
      assert.equal(manifest.capabilities.tools.every(tool => tool.readOnly === true), true)

      const gate = evaluatePublicationGate({
        registry: { entries: [] },
        catalog: {
          ...catalog,
          entries: rawEntries.map(entry => ({
            ...entry,
            executionRoute: entry.ingressRoute,
          })),
        },
      })
      kinds.forEach((kind, index) => {
        if (!['public-write', 'spend-wrong-route', 'hosted-direct-endpoint'].includes(kind)) return
        assert.equal(
          gate.blocks.some(block => block.subject === rawEntries[index].token),
          true,
        )
      })
    },
  ), { numRuns: PROPERTY_RUNS })
})

const digest = value => createHash('sha256').update(value).digest('hex')

// Feature: discoverability-ip-protection, Property 15: Blocks preserve state and report all causes.
test('Property 15: randomized independent causes and symmetric drift are complete and non-mutating', () => {
  fc.assert(fc.property(
    fc.uniqueArray(fc.integer({ min: 0, max: 100_000 }), { minLength: 1, maxLength: 30 }),
    fc.uniqueArray(fc.integer({ min: 0, max: 100_000 }), { minLength: 1, maxLength: 20 }),
    (causeIds, driftIds) => {
      const fixture = Object.fromEntries(causeIds.map(identifier => [
        `file-${identifier}.txt`,
        `fixture bytes ${identifier}`,
      ]))
      const beforeDigests = Object.fromEntries(
        Object.entries(fixture).map(([name, bytes]) => [name, digest(bytes)]),
      )
      const injectedBlocks = causeIds.map(identifier => ({
        criterionId: `R${identifier % 14}.1`,
        code: `FC-PROPERTY-${identifier}`,
        subject: `artifact-${identifier}`,
        detail: `blocking cause ${identifier}`,
      }))
      const actualOnly = driftIds.filter((_, index) => index % 2 === 0).map(id => `actual-${id}`)
      const expectedOnly = driftIds.filter((_, index) => index % 2 === 1).map(id => `expected-${id}`)
      const input = {
        registry: { entries: [] },
        parsedFiles: [{
          name: 'llms.txt',
          entries: actualOnly.map(entryId => ({ entryId })),
          expectedEntryIds: expectedOnly,
        }],
        injectedBlocks,
      }
      const beforeInput = structuredClone(input)
      const gate = evaluatePublicationGate(input, { now: () => FIXED_NOW })

      assert.equal(gate.decision, 'block')
      for (const block of injectedBlocks) {
        assert.equal(
          gate.blocks.some(candidate => candidate.code === block.code && candidate.subject === block.subject),
          true,
        )
      }
      const driftSubjects = gate.blocks
        .filter(block => block.code === 'FC-DRIFT')
        .map(block => block.subject)
        .sort()
      assert.deepEqual(driftSubjects, [...actualOnly, ...expectedOnly].sort())
      assert.deepEqual(input, beforeInput)
      assert.deepEqual(
        Object.fromEntries(Object.entries(fixture).map(([name, bytes]) => [name, digest(bytes)])),
        beforeDigests,
      )
      assert.equal(gate.statePreserved, true)
    },
  ), { numRuns: PROPERTY_RUNS })
})

const relationCase = fc.constantFrom('equal', 'subset', 'superset', 'disjoint')
const timeCase = fc.constantFrom('earlier', 'equal', 'later')

// Feature: discoverability-ip-protection, Property 16: Promotion requires an earlier matching instruction.
test('Property 16: instruction/attempt pairs satisfy the authorization biconditional', async () => {
  await fc.assert(fc.asyncProperty(
    fc.uniqueArray(fc.integer({ min: 0, max: 10_000 }), { minLength: 2, maxLength: 12 }),
    relationCase,
    fc.constantFrom('prod', 'edge'),
    fc.boolean(),
    timeCase,
    async (identifiers, relation, destination, destinationMatches, timing) => {
      const all = identifiers.map(identifier => `artifact-${identifier}`)
      let authorised = all
      let attempted = all
      if (relation === 'subset') attempted = all.slice(0, Math.max(1, all.length - 1))
      if (relation === 'superset') authorised = all.slice(0, Math.max(1, all.length - 1))
      if (relation === 'disjoint') attempted = all.map(id => `other-${id}`)
      const instructionTimestamp = timing === 'earlier'
        ? '2026-07-27T00:00:01.000Z'
        : timing === 'equal'
          ? FIXED_NOW
          : '2026-07-27T00:00:03.000Z'
      const instruction = {
        instructionId: 'instruction-property',
        artifactIds: authorised,
        destination,
        timestamp: instructionTimestamp,
      }
      const attempt = {
        destination: destinationMatches ? destination : destination === 'prod' ? 'edge' : 'prod',
        artifactIds: attempted,
        timestamp: FIXED_NOW,
      }
      const validation = validateOperatorInstruction(instruction, {
        attemptedAt: attempt.timestamp,
      })
      const expectedPermit = validation.ok
        && instruction.destination === attempt.destination
        && attempted.every(id => authorised.includes(id))
      const gate = evaluatePublicationGate({
        registry: { entries: [] },
        instruction,
        attempt,
      }, { now: () => FIXED_NOW })
      assert.equal(gate.decision === 'permit', expectedPermit)

      if (expectedPermit) {
        for (const artifactId of attempted) {
          const promotionRecord = {
            artifactId,
            sourcePath: `staging/${artifactId}`,
            destinationPath: `published/${artifactId}`,
            instructionId: instruction.instructionId,
            timestamp: attempt.timestamp,
          }
          assert.equal(validatePromotionRecord(promotionRecord).ok, true)
          let persisted = null
          const appendResult = await appendPromotionRecord(
            '/virtual/property-ledger',
            promotionRecord,
            {
              mkdir: async () => {},
              writeExclusive: async (_filePath, record) => {
                persisted = structuredClone(record)
              },
            },
          )
          assert.equal(appendResult.written, true)
          assert.deepEqual(persisted, promotionRecord)
        }
      } else {
        assert.equal(gate.blocks.some(block => block.code === 'FC-NO-APPROVAL'), true)
      }
    },
  ), { numRuns: PROPERTY_RUNS })
})

const conflictTier = fc.constantFrom(
  'private',
  'gated',
  'public-artifact',
  'public-discoverable',
)

// Feature: discoverability-ip-protection, Property 21: Conflicts resolve for protection.
test('Property 21: randomized conflicts emit at most one complete stub and overrides stay scoped', () => {
  fc.assert(fc.property(
    fc.array(fc.record({
      surfaceTier: conflictTier,
      completeStub: fc.boolean(),
      overrideKind: fc.constantFrom('none', 'valid', 'invalid'),
    }), { minLength: 1, maxLength: 20 }),
    cases => {
      const conflicts = cases.map((item, index) => ({
        conflictId: `conflict-${index}`,
        artifactId: `artifact-${index}`,
        capabilityName: item.completeStub ? `Capability ${index}` : '',
        summary: `Protection-first metadata ${index}.`,
        surfaceTier: item.surfaceTier,
        authorisationUrl: 'https://airvio.co/authorise',
      }))
      const overrides = cases.flatMap((item, index) => {
        if (item.overrideKind === 'none') return []
        return [{
          conflictId: `conflict-${index}`,
          author: 'operator',
          scope: `artifact-${index}`,
          justification: item.overrideKind === 'valid' ? 'Narrow reviewed exception.' : '',
        }]
      })
      const gate = evaluatePublicationGate({
        registry: { entries: [] },
        conflicts,
        overrides,
      }, { now: () => FIXED_NOW })

      const unresolved = cases.some(item => !(
        item.overrideKind === 'valid' && item.surfaceTier !== 'private'
      ))
      assert.equal(gate.decision === 'block', unresolved)
      assert.equal(gate.conflictRecords.length, conflicts.length)
      for (let index = 0; index < cases.length; index += 1) {
        const item = cases[index]
        const record = gate.conflictRecords.find(candidate => candidate.conflictId === `conflict-${index}`)
        assert.match(record.timestampUtc, /^\d{4}-\d{2}-\d{2}T/u)
        const overrideApplied = item.overrideKind === 'valid' && item.surfaceTier !== 'private'
        assert.equal(record.outcome === 'override-applied', overrideApplied)
        const stubs = gate.stubs.filter(stub => stub.capabilityName === `Capability ${index}`)
        assert.equal(stubs.length, !overrideApplied && item.completeStub ? 1 : 0)
        if (stubs.length === 1) {
          assert.deepEqual(Object.keys(stubs[0]).sort(), [
            'authorisationUrl',
            'capabilityName',
            'summary',
            'surfaceTier',
          ])
        }
        if (item.surfaceTier === 'private' && item.overrideKind !== 'none') {
          assert.equal(
            gate.blocks.some(block => block.code === 'FC-OVERRIDE' && block.subject === `conflict-${index}`),
            true,
          )
        }
      }
    },
  ), { numRuns: PROPERTY_RUNS })
})
