import test from "node:test";
import assert from "node:assert/strict";
import { BundleGraphStore } from "../../src/travel-commerce/bundle-graph-store.mjs";
import { EnvelopeLedger } from "../../src/travel-commerce/envelope-ledger.mjs";
import { ReoptWorker } from "../../src/travel-commerce/reopt-worker.mjs";
import { createTwoLegTravelCommerceRuntime } from "../../src/travel-commerce/wiring.mjs";
import { BalanceCache, OfferCache, deployBoundary, permittedModels } from "../../src/travel-commerce/edge-services.mjs";
import { CostLog, assertStoragePlacement } from "../../src/travel-commerce/runtime-guards.mjs";

test("affected set is downstream-only and excludes the changed leg", () => { const store = new BundleGraphStore("b"); for (const legId of ["a", "b", "sibling"]) assert.equal(store.insertLeg({ legId, principalId: "p", category: "x" }).kind, "ok"); store.insertEdge({ fromLegId: "a", toLegId: "b" }); assert.deepEqual(store.affectedSet("a").order, ["b"]); assert.equal(store.affectedSet("b").order.length, 0); });
test("ledger cannot overspend and releases are immediately visible", () => { const ledger = new EnvelopeLedger("p", 100); const first = ledger.checkAndReserve({ offerId: "a", amount: 70 }); assert.equal(first.kind, "reserved"); assert.equal(ledger.checkAndReserve({ offerId: "b", amount: 31 }).reason, "insufficient-envelope"); ledger.releaseHold(first.hold.holdId); assert.equal(ledger.availableBalance(), 100); });
test("cascade commits once with one net settlement and is idempotent", async () => { const calls = []; const { worker, store } = createTwoLegTravelCommerceRuntime({ settle: async call => calls.push(call) }); const event = { bundleId: "bundle-1", legId: "flight", eventId: "e-1" }; const first = await worker.handleMutation(event); const repeat = await worker.handleMutation(event); assert.equal(first.kind, "committed"); assert.equal(first.settlementCalls, 1); assert.equal(repeat, first); assert.equal(calls.length, 1); assert.equal(store.legs().find(leg => leg.legId === "experience").committedOfferId, "experience-new"); });
test("rejected quote rolls the snapshot back and makes no settlement", async () => { const store = new BundleGraphStore("b"); store.insertLeg({ legId: "a", principalId: "p", committedOfferId: "old-a", committedAmount: 10, category: "x" }); store.insertLeg({ legId: "b", principalId: "p", committedOfferId: "old-b", committedAmount: 10, category: "x" }); store.insertEdge({ fromLegId: "a", toLegId: "b" }); const worker = new ReoptWorker({ store, ledger: new EnvelopeLedger("p", 100), quote: async () => ({ kind: "rejected" }) }); const result = await worker.handleMutation({ bundleId: "b", legId: "a", eventId: "fail" }); assert.equal(result.kind, "rolled-back"); assert.equal(store.legs().find(leg => leg.legId === "b").committedOfferId, "old-b"); });
test("settlement failure restores the bundle and releases reserved holds", async () => { const store = new BundleGraphStore("b"); store.insertLeg({ legId: "a", principalId: "p", committedOfferId: "old-a", committedAmount: 10, category: "x" }); store.insertLeg({ legId: "b", principalId: "p", committedOfferId: "old-b", committedAmount: 10, category: "x" }); store.insertEdge({ fromLegId: "a", toLegId: "b" }); const ledger = new EnvelopeLedger("p", 100); const worker = new ReoptWorker({ store, ledger, quote: async () => ({ kind: "offer", offerId: "new", amount: 20 }), settle: async () => { throw new Error("settlement-failed"); } }); const result = await worker.handleMutation({ bundleId: "b", legId: "a", eventId: "settle-fail" }); assert.equal(result.kind, "rolled-back"); assert.equal(ledger.availableBalance(), 100); assert.equal(store.legs().find(leg => leg.legId === "b").committedOfferId, "old-b"); });
test("edge services retain fail-closed boundaries", () => { const cache = new BalanceCache(); cache.set("p", 9); assert.equal(cache.get("p").mustConfirm, true); assert.throws(() => new OfferCache(1)); assert.equal(permittedModels(null).reason, "license-configuration-unavailable"); assert.equal(deployBoundary({ target: "Prod_Mirror" }).reason, "boundary-crossing-forbidden"); });
test("every cascade records a zero-token orchestration cost and rejects hot-path D1", async () => { const costLog = new CostLog(); const { worker } = createTwoLegTravelCommerceRuntime(); worker.costLog = costLog; await worker.handleMutation({ bundleId: "bundle-1", legId: "experience", eventId: "noop" }); assert.deepEqual(costLog.entries()[0].promptTokens, 0); assert.equal(assertStoragePlacement({ caller: "reopt-worker", purpose: "aggregate-reporting" }).reason, "storage-placement"); });
