/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/agenticgraph-storage/wrangler.toml --include-runtime=false --env-interface=AgenticGraphStorageBindings cloudflare/workers/agenticgraph-storage/worker-configuration.d.ts` (hash: 5ce9d775b6d50a5b97cc0f06d478d02b)
interface __BaseEnv_AgenticGraphStorageBindings {
	AGENTICGRAPH_STORAGE_BLOB_BUCKET: R2Bucket;
	DB: D1Database;
	SHARED_NODE_MAX_DELTA_BYTES: "65536";
	SHARED_NODE_MAX_PAYLOAD_BYTES: "262144";
	SHARED_NODE_REPLAY_LOG_MAX_ENTRIES: "128";
	SHARED_NODE_TRAVEL_DISPATCH_TIMEOUT_MS: "12000";
	AGENTICGRAPH_STORAGE_LOCAL_RUNTIME: "false";
	AGENTICGRAPH_CANVAS_ROOM: DurableObjectNamespace<import("./index").AgenticGraphCanvasSyncRoom>;
	AGENTICGRAPH_TRAVEL_COMMERCE: Fetcher /* agenticgraph-travel-commerce-production */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "AgenticGraphCanvasSyncRoom";
	}
	interface Env extends __BaseEnv_AgenticGraphStorageBindings {}
}
interface AgenticGraphStorageBindings extends __BaseEnv_AgenticGraphStorageBindings {}
