/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/knowgrph-storage/wrangler.toml --include-runtime=false --env-interface=KnowgrphStorageBindings cloudflare/workers/knowgrph-storage/worker-configuration.d.ts` (hash: 96c5a485a7f30f7f6fe1fa86a9b29ed0)
interface __BaseEnv_KnowgrphStorageBindings {
	KNOWGRPH_STORAGE_BLOB_BUCKET: R2Bucket;
	DB: D1Database;
	KNOWGRPH_CANVAS_ROOM: DurableObjectNamespace<import("./index").KnowgrphCanvasSyncRoom>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "KnowgrphCanvasSyncRoom";
	}
	interface Env extends __BaseEnv_KnowgrphStorageBindings {}
}
interface KnowgrphStorageBindings extends __BaseEnv_KnowgrphStorageBindings {}
