/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/knowgrph-storage/wrangler.toml --include-runtime=false --env-interface=KnowgrphStorageBindings cloudflare/workers/knowgrph-storage/worker-configuration.d.ts` (hash: 6d28ad65f541876769da33e01aee8ffd)
interface __BaseEnv_KnowgrphStorageBindings {
	KNOWGRPH_STORAGE_BLOB_BUCKET: R2Bucket;
	DB: D1Database;
	SHARED_NODE_MAX_DELTA_BYTES: "65536";
	SHARED_NODE_MAX_PAYLOAD_BYTES: "262144";
	SHARED_NODE_REPLAY_LOG_MAX_ENTRIES: "128";
	SHARED_NODE_TRAVEL_DISPATCH_TIMEOUT_MS: "12000";
	KNOWGRPH_CANVAS_ROOM: DurableObjectNamespace<import("./index").KnowgrphCanvasSyncRoom>;
	KNOWGRPH_TRAVEL_COMMERCE: Fetcher /* knowgrph-travel-commerce-production */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "KnowgrphCanvasSyncRoom";
	}
	interface Env extends __BaseEnv_KnowgrphStorageBindings {}
}
interface KnowgrphStorageBindings extends __BaseEnv_KnowgrphStorageBindings {}
