/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/knowgrph-travel-settlement-executor/wrangler.jsonc --include-runtime=false --env-interface=SettlementExecutorEnv cloudflare/workers/knowgrph-travel-settlement-executor/worker-configuration.d.ts` (hash: 605fffdb518c8dc4daaa3ba9bfc53c23)
interface __BaseEnv_SettlementExecutorEnv {
	ISSUANCE_SERVICE_BASE_URL: "https://issuance-service-staging.invalid" | "https://issuance-service-production.invalid" | "https://issuance-service-dev.invalid";
	ISSUANCE_SERVICE_TIMEOUT_MS: "5000";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface StagingEnv {
		ISSUANCE_SERVICE_BASE_URL: "https://issuance-service-staging.invalid";
		ISSUANCE_SERVICE_TIMEOUT_MS: "5000";
	}
	interface ProductionEnv {
		ISSUANCE_SERVICE_BASE_URL: "https://issuance-service-production.invalid";
		ISSUANCE_SERVICE_TIMEOUT_MS: "5000";
	}
	interface Env extends __BaseEnv_SettlementExecutorEnv {}
}
interface SettlementExecutorEnv extends __BaseEnv_SettlementExecutorEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ISSUANCE_SERVICE_BASE_URL" | "ISSUANCE_SERVICE_TIMEOUT_MS">> {}
}
