import type { MainPanelFieldHelp } from '../ui/mainPanelRowHelp'

const field = (actions: string[], outcome: string, defaultValue = 'N/A (runtime)', impact = 'Observed session state; updates as peers connect.'): MainPanelFieldHelp => ({
  role: 'Collaborator', actions, outcome,
  value: { key: 'collaboration', type: 'string', defaultValue, impact },
})
export const collaborationFieldHelp = {
  displayName: field(['set the name shown to peers'], 'identify this device in the shared session', 'Device-derived peer name', 'Changes the name visible to connected peers.'),
  session: field(['inspect session phase and ownership'], 'confirm which session and peer own the connection'),
  peerCount: field(['inspect total, remote and connected peers'], 'distinguish available peers from active connections'),
  runtime: field(['inspect collaboration runtime status'], 'observe connection progress or failure'),
  follow: field(['enable or disable following the selected peer'], 'synchronize the local view with an explicit peer', 'Off', 'On follows the selected peer; Off keeps local navigation independent.'),
  connection: field(['start or disconnect a session'], 'establish or release the current collaboration transport', 'Disconnected', 'Connect starts the configured transport; disconnect releases it.'),
  invite: field(['copy the generated invite for one guest'], 'allow the intended guest to join this session', 'Empty', 'Generated by the host; each guest needs its own invite.'),
  join: field(['paste and join a host invite'], 'create a guest connection to the selected host', 'Empty', 'Accepts an invite URL or token; joining starts a connection.'),
  answer: field(['copy the guest answer for the host'], 'return the handshake response to the session owner', 'Empty', 'Generated after joining an invite.'),
  apply: field(['apply the guest answer token'], 'finish the host to guest handshake', 'Empty', 'Connect applies the supplied guest answer.'),
  peer: field(['inspect or follow this peer'], 'navigate with an explicitly selected participant'),
  transport: field(['inspect the active transport'], 'confirm the session relay and synchronization status'),
} satisfies Record<string, MainPanelFieldHelp>
