import test from 'node:test'
import assert from 'node:assert/strict'
import { createHash } from 'node:crypto'
import fs from 'node:fs'
import fsPromises from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { buildPagesMirrorAgentReadyPlan } from '../pages-mirror-agent-ready.mjs'
import { buildAgentReadyHeaders } from '../pages-mirror-headers.mjs'
import { buildAgenticGraphRedirects } from '../production-pages-routing.mjs'
import { productionRuntimeReadinessHeaderLines } from '../production-runtime-readiness-build.mjs'
import {
  assertSealedLegacyContentInventory,
  assertSealedLegacyFileDigestInventory,
  digestRelativeFileContents,
} from '../legacy-mirror-inventory.mjs'
import { createPagesMirrorLegacyCleanup } from '../pages-mirror-legacy-cleanup.mjs'
import {
  XR_V2_LEGACY_MIRROR_RELATIVE_PATHS,
  XR_V2_LEGACY_MIRROR_SHA256_BY_PATH,
  XR_V2_MIRRORED_IGNORE_RELATIVE_PATH,
  XR_V2_PUBLISH_RUNTIME_RELATIVE_PATHS,
} from '../xr-v2/production-publish-contract.mjs'

const repoRoot = path.resolve(import.meta.dirname, '..', '..')
const readScript = filename => fs.readFileSync(path.resolve(repoRoot, 'scripts', filename), 'utf8')
const syncSource = readScript('pages-mirror-sync.mjs')
const cleanupSource = readScript('pages-mirror-legacy-cleanup.mjs')
const inventorySource = readScript('legacy-mirror-inventory.mjs')

const buildPlan = async t => {
  const mirrorRoot = await fsPromises.mkdtemp(path.join(os.tmpdir(), 'agentic-graph-pages-plan-'))
  t.after(() => fsPromises.rm(mirrorRoot, { force: true, recursive: true }))
  const plan = await buildPagesMirrorAgentReadyPlan({ agenticGraphRoot: repoRoot, mirrorRoot })
  return { mirrorRoot, plan }
}

const copyTargetPaths = (plan, mirrorRoot) => new Set(plan.agentReadyRuntimeCopies.map(([, target]) => (
  path.relative(mirrorRoot, target).split(path.sep).join('/')
)))

test('publish sync removes stale generated assets through a sealed legacy boundary', () => {
  assert.doesNotMatch(syncSource, /isRetainedAssetRelativePath/)
  assert.match(syncSource, /const isPublicManagedRelativePath = relativePath => Boolean\(relativePath\)/)
  assert.match(syncSource, /filesToRemove\.push\(relativePath\)/)
  assert.match(syncSource, /publicFilesToRemove\.push\(relativePath\)/)
  assert.match(syncSource, /await createLegacyMigrationPlan\(\{ obsoleteGeneratedMirrorFiles \}\)/)
  assert.equal(
    syncSource.match(/await assertLegacyMirrorInventoryIsBounded\(\)/g)?.length,
    1,
    'expected a fresh post-cleanup inventory check after the combined preflight',
  )
  assert.match(cleanupSource, /listSealedLegacyMirrorEntries/)
  assert.match(cleanupSource, /removeLegacyMirrorFiles/)
  assert.match(cleanupSource, /Legacy image migration refuses to overwrite/)
  assert.match(inventorySource, /Legacy mirror root inventory drifted/)
  assert.match(inventorySource, /content drifted/)
  assert.match(inventorySource, /Legacy named-file inventory contains an unexpected, missing, or partially retired path/)
})

test('legacy XR cleanup is sealed to the five protected-revision file digests', async () => {
  assert.deepEqual(XR_V2_LEGACY_MIRROR_SHA256_BY_PATH, {
    'content/knowgrph/xr-v2/models/depth-anything-v2-small/config.json': '3aee5b9bc4f711ee885c2526d871f0c8c6c8c4b26b8e04253d0167f6a83264f5',
    'content/knowgrph/xr-v2/models/depth-anything-v2-small/preprocessor_config.json': '03576db3c13dd0471fdf5f5e1428befcb95de063fe699879150b293dc9e0a2c6',
    'content/knowgrph/xr-v2/models/depth-anything-v2-small/onnx/model_q4f16.onnx': 'eca72971aea64216d767c70c534160de53b5435b588d362bac6dbd5a73f9bf1e',
    'content/knowgrph/xr-v2/wasm/ort-wasm-simd-threaded.mjs': '5f2cd914554830762579c372d0211614c1e3f40ab3f6c0cfcf0900343229071d',
    'content/knowgrph/xr-v2/wasm/ort-wasm-simd-threaded.wasm': 'f4f290847a4df02d0b93cdbf39b4b0e71acefbe80573e7e6b9342a7abd7b290a',
  })
  assert.deepEqual(Object.keys(XR_V2_LEGACY_MIRROR_SHA256_BY_PATH), XR_V2_LEGACY_MIRROR_RELATIVE_PATHS)
  const modifiedFiles = new Map(
    XR_V2_LEGACY_MIRROR_RELATIVE_PATHS.map(relativePath => [relativePath, Buffer.from(`modified ${relativePath}\n`)]),
  )
  await assert.rejects(
    assertSealedLegacyFileDigestInventory({
      sha256ByPath: XR_V2_LEGACY_MIRROR_SHA256_BY_PATH,
      readRelativeFile: async relativePath => modifiedFiles.get(relativePath) ?? null,
      label: 'Legacy XR v2 file inventory',
    }),
    /Legacy XR v2 file inventory content drifted/,
  )
})

test('legacy cleanup revalidates planned bytes immediately before unlink', async t => {
  const mirrorRoot = await fsPromises.mkdtemp(path.join(os.tmpdir(), 'agentic-graph-legacy-cleanup-race-'))
  t.after(() => fsPromises.rm(mirrorRoot, { force: true, recursive: true }))
  const relativePath = 'index.html'
  const filePath = path.resolve(mirrorRoot, relativePath)
  await fsPromises.writeFile(filePath, 'generated bytes\n')
  const cleanup = createPagesMirrorLegacyCleanup({ mirrorRoot })
  const plan = await cleanup.collectLegacyMirrorFilesToRemove({
    obsoleteGeneratedMirrorFiles: new Set([relativePath]),
  })
  await fsPromises.writeFile(filePath, 'operator replacement\n')

  await assert.rejects(
    cleanup.removeLegacyMirrorFiles(plan),
    /Planned legacy mirror deletion content drifted for index\.html/,
  )
  assert.equal(await fsPromises.readFile(filePath, 'utf8'), 'operator replacement\n')
})

test('legacy image migration revalidates planned source bytes immediately before copy', async t => {
  const mirrorRoot = await fsPromises.mkdtemp(path.join(os.tmpdir(), 'agentic-graph-legacy-copy-race-'))
  t.after(() => fsPromises.rm(mirrorRoot, { force: true, recursive: true }))
  const sourceRelativePath = 'image/agenticgraph/xr/frame.png'
  const sourcePath = path.resolve(mirrorRoot, sourceRelativePath)
  const destinationPath = path.resolve(mirrorRoot, 'image/agentic-graph/xr/frame.png')
  const original = Buffer.from('sealed source bytes\n')
  await fsPromises.mkdir(path.dirname(sourcePath), { recursive: true })
  await fsPromises.writeFile(sourcePath, original)
  const cleanup = createPagesMirrorLegacyCleanup({ mirrorRoot })
  const entry = {
    sourceRelativePath,
    sourceSha256: createHash('sha256').update(original).digest('hex'),
    destinationPath,
  }
  await fsPromises.writeFile(sourcePath, 'operator replacement\n')

  await assert.rejects(
    cleanup.copyLegacyImageFile(entry),
    /Planned legacy image copy content drifted/,
  )
  await assert.rejects(fsPromises.stat(destinationPath), { code: 'ENOENT' })
})

test('sealed legacy cleanup refuses a byte-modified tracked path', async () => {
  const files = new Map([
    ['one.txt', Buffer.from('one\n')],
    ['two.txt', Buffer.from('two\n')],
  ])
  const sha256 = value => createHash('sha256').update(value).digest('hex')
  const relativePaths = [...files.keys()]
  const inventory = {
    count: relativePaths.length,
    contentDigest: digestRelativeFileContents(relativePaths.map(relativePath => ({
      relativePath,
      sha256: sha256(files.get(relativePath)),
    }))),
  }
  const readRelativeFile = async relativePath => files.get(relativePath) ?? null
  await assertSealedLegacyContentInventory({
    relativePaths,
    readRelativeFile,
    inventory,
    label: 'Fixture legacy inventory',
  })
  files.set('two.txt', Buffer.from('operator-authored bytes\n'))
  await assert.rejects(
    assertSealedLegacyContentInventory({
      relativePaths,
      readRelativeFile,
      inventory,
      label: 'Fixture legacy inventory',
    }),
    /content drifted/,
  )
})

test('published agent-ready dependency plan contains the browser and tool-contract closure', async t => {
  const { mirrorRoot, plan } = await buildPlan(t)
  const targets = copyTargetPaths(plan, mirrorRoot)
  for (const relativePath of [
    'canvas/src/features/agent-ready/browserFunctionSource.mjs',
    'canvas/src/features/agent-ready/publishedToolExecutors.mjs',
    'canvas/src/features/agent-ready/webMcpLifecycle.mjs',
    'canvas/src/features/agent-ready/webMcpLifecycleBrowserSource.mjs',
    'canvas/src/features/agent-ready/agentic-graph-agent-ready-output-schemas.mjs',
    'canvas/src/features/agent-ready/mcpAppsContractText.mjs',
    'canvas/src/features/agent-ready/mcpAppsOnboarding.mjs',
    'canvas/src/features/agent-ready/motionControlAgentReadyContract.mjs',
    'canvas/src/features/agent-ready/flightSimAgentReadyContract.mjs',
    'canvas/src/features/agent-ready/storageSyncAgentReadyContract.mjs',
    'canvas/src/features/agent-ready/probeTreeUserInputRelevance.mjs',
    'canvas/src/features/agent-ready/agentic-graph-vdeoxpln-registry-data.mjs',
    'canvas/src/features/agent-ready/agentic-graph-application-composition-vdeoxpln.mjs',
    'canvas/src/features/group-panel/groupPanelContract.mjs',
    'canvas/src/features/three/xrSceneMcpContract.mjs',
    'canvas/src/features/three/xrAnimationMcpContract.mjs',
    'canvas/src/features/three/motionControlMcpContract.mjs',
    'canvas/src/features/game-flight-sim/flightSimMcpContract.mjs',
    'canvas/src/features/strybldr/cameraMcpContract.mjs',
    'canvas/src/lib/storage/agentic-graph-storage-engine-mcp-contract.mjs',
    'contracts/semantic-key.js',
    'grph-shared/dist/payments/agenticCommercePaidResourceSsot.js',
    'grph-shared/dist/payments/xrplClassicAddress.js',
  ]) {
    assert.ok(targets.has(relativePath), `missing published dependency ${relativePath}`)
  }
})

test('publish sync retains the canonical root shell and one managed 404 boundary', () => {
  assert.match(syncSource, /'agentic-graph-live-canvas-hero\.md'/)
  assert.match(syncSource, /rel: '404\.html'/)
  assert.match(syncSource, /cloudflare', 'pages', '404\.html'/)
  assert.match(syncSource, /'index\.html', \.\.\.XR_V2_LEGACY_MIRROR_RELATIVE_PATHS/)
})

test('generated headers cover mutable service-worker paths without retaining legacy product routes', () => {
  const headers = buildAgentReadyHeaders({
    existing: [
      '/agenticgraph/*',
      '  Cache-Control: public, max-age=31536000',
      '',
      '# BEGIN knowgrph generated old headers',
      '/knowgrph/*',
      '  Cache-Control: public, max-age=31536000',
      '# END knowgrph generated old headers',
      '',
    ].join('\n'),
    artifacts: { '.well-known/agent-ready.json': { body: '{}', contentType: 'application/json' } },
    agentReadyHomepageLinkHeaderValue: '<https://airvio.co/.well-known/agent-ready.json>; rel="agent-ready"',
    productionRuntimeReadinessHeaderLines,
  })
  assert.doesNotMatch(headers, /\/(?:agenticgraph|knowgrph)(?:\/|\*)/)
  for (const route of [
    '/content/agentic-graph/sw.js',
    '/agentic-graph/sw.js',
    '/content/agentic-graph/agentic-graph-chat-stream-sw.js',
    '/agentic-graph/agentic-graph-chat-stream-sw.js',
    '/content/agentic-graph/agentic-graph-service-worker-revision.js',
    '/agentic-graph/agentic-graph-service-worker-revision.js',
  ]) assert.match(headers, new RegExp(`${route.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\n  Cache-Control: no-store`))
})

test('runtime readiness includes generated service-worker executables and exact XR v2 assets', () => {
  assert.match(syncSource, /agentic-graph-chat-stream-sw\.js/)
  assert.match(syncSource, /agentic-graph-service-worker-revision\.js/)
  assert.match(syncSource, /isBrowserRuntimeArtifactRelativePath/)
  assert.match(syncSource, /XR_V2_MIRRORED_IGNORE_RELATIVE_PATH/)
  assert.match(syncSource, /XR_V2_PUBLISH_RUNTIME_RELATIVE_PATHS/)
  const expectedRuntimePaths = [
    'xr-v2/models/depth-anything-v2-small/config.json',
    'xr-v2/models/depth-anything-v2-small/preprocessor_config.json',
    'xr-v2/models/depth-anything-v2-small/onnx/model_q4f16.onnx',
    'xr-v2/wasm/ort-wasm-simd-threaded.mjs',
    'xr-v2/wasm/ort-wasm-simd-threaded.wasm',
  ]
  assert.deepEqual(XR_V2_PUBLISH_RUNTIME_RELATIVE_PATHS, expectedRuntimePaths)
  assert.deepEqual(XR_V2_LEGACY_MIRROR_RELATIVE_PATHS, expectedRuntimePaths.map(relativePath => `content/knowgrph/${relativePath}`))
  assert.equal(XR_V2_MIRRORED_IGNORE_RELATIVE_PATH, 'xr-v2/.gitignore')
})

test('XR v2 root and canonical routes precede the agentic-graph SPA fallback', () => {
  const rootRoute = '/xr-v2/* /content/agentic-graph/xr-v2/:splat 200'
  const canonicalRoute = '/agentic-graph/xr-v2/* /content/agentic-graph/xr-v2/:splat 200'
  const fallback = '/agentic-graph/* /content/agentic-graph/index.html 200'
  const redirects = buildAgenticGraphRedirects({
    existing: ['/agentic-graph/imports/* /content/agentic-graph/imports/:splat 200', fallback, ''].join('\n'),
    rootFiles: [],
  })
  assert.ok(redirects.includes(rootRoute))
  assert.ok(redirects.includes(canonicalRoute))
  assert.ok(redirects.indexOf(rootRoute) < redirects.indexOf(fallback))
  assert.ok(redirects.indexOf(canonicalRoute) < redirects.indexOf(fallback))
})

test('only the canonical namespace receives generated routes', () => {
  const existingRoutes = ''
  const rootFiles = ['agentic-graph-chat-stream-sw.js', 'manifest.webmanifest']
  const redirects = buildAgenticGraphRedirects({ existing: existingRoutes, rootFiles })
  assert.match(redirects, /# BEGIN agentic-graph generated namespace routes/)
  assert.match(redirects, /\/agentic-graph \/content\/agentic-graph\/index\.html 200/)
  assert.doesNotMatch(redirects, /\/old\b/)
  assert.equal(buildAgenticGraphRedirects({ existing: redirects, rootFiles }), redirects)
})

test('legacy source docs migrate losslessly before deletion, retry safely, and reject destination drift', async t => {
  const mirrorRoot = await fsPromises.mkdtemp(path.join(os.tmpdir(), 'agentic-graph-doc-migration-'))
  t.after(() => fsPromises.rm(mirrorRoot, { recursive: true, force: true }))
  const relativePath = 'docs/agenticgraph-agentic-video-canvas-demo.md'
  const destination = path.join(mirrorRoot, 'docs/agentic-graph-agentic-video-canvas-demo.md')
  const source = path.join(mirrorRoot, relativePath)
  const bytes = Buffer.from('---\ntitle: Authored source\n---\nExact bytes: π\r\n')
  await fsPromises.mkdir(path.dirname(source), { recursive: true })
  await fsPromises.writeFile(source, bytes)
  const entry = { relativePath, sha256: createHash('sha256').update(bytes).digest('hex') }
  const cleanup = createPagesMirrorLegacyCleanup({ mirrorRoot })
  await assert.rejects(cleanup.removeLegacyMirrorFiles([entry]))
  assert.deepEqual(await fsPromises.readFile(source), bytes)
  await cleanup.copyLegacyDocumentFile(entry)
  await cleanup.copyLegacyDocumentFile(entry)
  assert.deepEqual(await fsPromises.readFile(destination), bytes)
  await fsPromises.writeFile(destination, 'operator replacement')
  await assert.rejects(cleanup.copyLegacyDocumentFile(entry), /refuses to overwrite/)
  await assert.rejects(cleanup.removeLegacyMirrorFiles([entry]), /content drifted/)
  assert.deepEqual(await fsPromises.readFile(source), bytes)
  await fsPromises.writeFile(destination, bytes)
  await cleanup.removeLegacyMirrorFiles([entry])
  await assert.rejects(fsPromises.stat(source), { code: 'ENOENT' })
  assert.deepEqual(await fsPromises.readFile(destination), bytes)
})

test('legacy document copy rejects changed source and paths outside the finite migration map', async t => {
  const mirrorRoot = await fsPromises.mkdtemp(path.join(os.tmpdir(), 'agentic-graph-doc-source-'))
  t.after(() => fsPromises.rm(mirrorRoot, { recursive: true, force: true }))
  const relativePath = 'docs/agenticgraph-strybldr-starter-template.md'
  await fsPromises.mkdir(path.join(mirrorRoot, 'docs'))
  await fsPromises.writeFile(path.join(mirrorRoot, relativePath), 'changed')
  const cleanup = createPagesMirrorLegacyCleanup({ mirrorRoot })
  await assert.rejects(cleanup.copyLegacyDocumentFile({ relativePath, sha256: createHash('sha256').update('original').digest('hex') }), /content drifted/)
  await assert.rejects(cleanup.copyLegacyDocumentFile({ relativePath: 'docs/agenticgraph-unknown.md', sha256: 'a'.repeat(64) }), /outside the sealed source inventory/)
  assert.deepEqual(await fsPromises.readdir(path.join(mirrorRoot, 'docs')), ['agenticgraph-strybldr-starter-template.md'])
})

test('combined migration preflight scans the sealed roots once and refreshes on every invocation', async t => {
  const mirrorRoot = await fsPromises.mkdtemp(path.join(os.tmpdir(), 'agentic-graph-migration-scan-'))
  t.after(() => fsPromises.rm(mirrorRoot, { recursive: true, force: true }))
  await fsPromises.writeFile(path.join(mirrorRoot, 'index.html'), 'old generated file')
  const original = fsPromises.readdir
  let sealedRootReads = 0
  t.mock.method(fsPromises, 'readdir', async (...args) => {
    if (args[0] === path.join(mirrorRoot, 'content/agenticgraph')) sealedRootReads += 1
    return original(...args)
  })
  const cleanup = createPagesMirrorLegacyCleanup({ mirrorRoot })
  const options = { obsoleteGeneratedMirrorFiles: ['index.html'] }
  const first = await cleanup.createLegacyMigrationPlan(options)
  assert.equal(sealedRootReads, 1)
  assert.equal(first.legacyMirrorFilesToRemove.length, 1)
  assert.deepEqual(first.legacyDocumentMigration, [])
  await fsPromises.writeFile(path.join(mirrorRoot, 'index.html'), 'new generated file')
  const second = await cleanup.createLegacyMigrationPlan(options)
  assert.equal(sealedRootReads, 2)
  assert.notEqual(second.legacyMirrorFilesToRemove[0].sha256, first.legacyMirrorFilesToRemove[0].sha256)
  await assert.rejects(cleanup.removeLegacyMirrorFiles(first.legacyMirrorFilesToRemove), /content drifted/)
  assert.equal(await fsPromises.readFile(path.join(mirrorRoot, 'index.html'), 'utf8'), 'new generated file')
})

const generatePolicyHeaders = existing => buildAgentReadyHeaders({
  existing,
  artifacts: {},
  agentReadyHomepageLinkHeaderValue: '<https://example.invalid/agent.json>; rel="agent-ready"',
  productionRuntimeReadinessHeaderLines,
})

test('generated headers preserve authored content policies and adjacent unrelated routes', () => {
  const report = "  Content-Security-Policy-Report-Only: default-src 'self'; object-src 'none'"
  const enforced = "  Content-Security-Policy: frame-ancestors 'self'"
  const unrelated = '/unrelated/*\n  X-Example: retained'
  const existing = ['/agenticgraph/*', report, unrelated, 'https://example.invalid/remote/*', '  X-Remote: retained', '/content/knowgrph/*', '  ! Content-Security-Policy', enforced, '/knowgrph/*', report, ''].join('\n')
  const output = generatePolicyHeaders(existing)
  assert.ok(output.includes('/agentic-graph/*\n' + report))
  assert.ok(output.includes('/content/agentic-graph/*\n  ! Content-Security-Policy\n' + enforced))
  assert.ok(output.includes(unrelated))
  assert.ok(output.includes('https://example.invalid/remote/*\n  X-Remote: retained'))
  assert.equal(output.split(report).length - 1, 1)
  assert.doesNotMatch(output, /^\/(?:content\/)?(?:agenticgraph|knowgrph)(?:\/|\*)/m)
})

test('generated headers reject conflicting legacy policies and retain explicit canonical policy', () => {
  const a = "  Content-Security-Policy-Report-Only: default-src 'self'"
  const b = "  Content-Security-Policy-Report-Only: default-src 'none'"
  const legacy = ['/agenticgraph/*', a, '', '/knowgrph/*', b, ''].join('\n')
  assert.throws(() => generatePolicyHeaders(legacy), /conflicting legacy content policies/)
  const output = generatePolicyHeaders(legacy + '\n/agentic-graph/*\n' + b + '\n')
  assert.ok(output.includes('/agentic-graph/*\n' + b))
  assert.ok(!output.includes(a))
  assert.equal(output.split(b).length - 1, 1)
})

test('generated headers have stable bytes immediately after first generation', () => {
  const once = generatePolicyHeaders('/*\n  X-Content-Type-Options: nosniff\n')
  const twice = generatePolicyHeaders(once)
  assert.equal(twice, once)
  assert.equal(generatePolicyHeaders(twice), twice)
  assert.ok(once.endsWith('\n') && !once.endsWith('\n\n'))
})
