/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/agenticgraph-travel-commerce/wrangler.jsonc --include-runtime=false --env-interface=TravelCommerceEnv cloudflare/workers/agenticgraph-travel-commerce/worker-configuration.d.ts` (hash: f3397245c932607fed80d2b0d867517e)
interface __BaseEnv_TravelCommerceEnv {
	BALANCE_CACHE: KVNamespace;
	PROVENANCE_ARCHIVE: R2Bucket;
	AI: Ai;
	DEPLOY_LANE: "Staging_Lane" | "Production_Lane" | "Dev_Lane";
	CASCADE_WALL_MS: "10000";
	SETTLEMENT_CURRENCY: "SGD";
	TRAVEL_GUARDRAIL_RETRY_BOUND: "3";
	TRAVEL_INTENT_MIN_BUDGET_MINOR: "1";
	TRAVEL_INTENT_MAX_BUDGET_MINOR: "9007199254740991";
	MODEL_CATALOG_JSON: "[{\"id\":\"@cf/openai/gpt-oss-20b\",\"provider_id\":\"@cf/openai/gpt-oss-20b\",\"license\":\"Apache-2.0\",\"path\":\"workers-ai-free\",\"free_daily_neuron_limit\":10000},{\"id\":\"@cf/openai/gpt-oss-20b-free-overflow\",\"provider_id\":\"@cf/openai/gpt-oss-20b\",\"license\":\"Apache-2.0\",\"path\":\"workers-ai-free-overflow\",\"free_daily_neuron_limit\":10000}]";
	PERMITTED_MODEL_LICENSES_JSON: "[\"Apache-2.0\",\"MIT\"]";
	COMMERCE_PROVIDER_SOURCE_REVISION: "0000000000000000000000000000000000000000";
	COMMERCE_PROVIDER_STORAGE_REVISION: "commerce-checkout-do-sqlite-v1";
	COMMERCE_PROVIDER_VERSION_ID: "staging-unreleased" | "production-unreleased" | "local-unreleased";
	TRAVEL_COMMERCE_API_TOKEN: string;
	RECONCILIATION_OPERATOR_TOKEN: string;
	INFERENCE_OVERFLOW_TOKEN: string;
	CHECKOUT_PROVIDER_AUTH_SECRET: string;
	MARKETPLACE_PROVIDER_AUTH_SECRET: string;
	BUNDLE_GRAPH: DurableObjectNamespace<import("./src/index").BundleGraphStore>;
	ENVELOPE_LEDGER: DurableObjectNamespace<import("./src/index").EnvelopeLedger>;
	CHECKOUT_PROVIDER_STORE: DurableObjectNamespace<import("./src/index").CommerceCheckoutStore>;
	DISCOVERY_SERVICE: Fetcher /* agenticgraph-mcp-staging */ | Fetcher /* agenticgraph-mcp */ | Fetcher /* agenticgraph-mcp-dev */;
	ISSUANCE_SERVICE: Fetcher /* agenticgraph-travel-net-settlement-staging */ | Fetcher /* agenticgraph-travel-net-settlement-production */ | Fetcher /* agenticgraph-travel-net-settlement-dev */;
	MARKETPLACE_SERVICE: Fetcher /* agenticgraph-marketplace-staging */ | Fetcher /* agenticgraph-marketplace-production */ | Fetcher /* agenticgraph-marketplace-dev */;
	INFERENCE_OVERFLOW: Fetcher /* agenticgraph-travel-ollama-overflow-staging */ | Fetcher /* agenticgraph-travel-ollama-overflow */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "BundleGraphStore" | "EnvelopeLedger" | "CommerceCheckoutStore";
	}
	interface StagingEnv {
		BALANCE_CACHE: KVNamespace;
		PROVENANCE_ARCHIVE: R2Bucket;
		AI: Ai;
		DEPLOY_LANE: "Staging_Lane";
		CASCADE_WALL_MS: "10000";
		SETTLEMENT_CURRENCY: "SGD";
		TRAVEL_GUARDRAIL_RETRY_BOUND: "3";
		TRAVEL_INTENT_MIN_BUDGET_MINOR: "1";
		TRAVEL_INTENT_MAX_BUDGET_MINOR: "9007199254740991";
		MODEL_CATALOG_JSON: "[{\"id\":\"@cf/openai/gpt-oss-20b\",\"provider_id\":\"@cf/openai/gpt-oss-20b\",\"license\":\"Apache-2.0\",\"path\":\"workers-ai-free\",\"free_daily_neuron_limit\":10000},{\"id\":\"@cf/openai/gpt-oss-20b-free-overflow\",\"provider_id\":\"@cf/openai/gpt-oss-20b\",\"license\":\"Apache-2.0\",\"path\":\"workers-ai-free-overflow\",\"free_daily_neuron_limit\":10000}]";
		PERMITTED_MODEL_LICENSES_JSON: "[\"Apache-2.0\",\"MIT\"]";
		COMMERCE_PROVIDER_SOURCE_REVISION: "0000000000000000000000000000000000000000";
		COMMERCE_PROVIDER_STORAGE_REVISION: "commerce-checkout-do-sqlite-v1";
		COMMERCE_PROVIDER_VERSION_ID: "staging-unreleased";
		TRAVEL_COMMERCE_API_TOKEN: string;
		RECONCILIATION_OPERATOR_TOKEN: string;
		INFERENCE_OVERFLOW_TOKEN: string;
		CHECKOUT_PROVIDER_AUTH_SECRET: string;
		MARKETPLACE_PROVIDER_AUTH_SECRET: string;
		BUNDLE_GRAPH: DurableObjectNamespace<import("./src/index").BundleGraphStore>;
		ENVELOPE_LEDGER: DurableObjectNamespace<import("./src/index").EnvelopeLedger>;
		CHECKOUT_PROVIDER_STORE: DurableObjectNamespace<import("./src/index").CommerceCheckoutStore>;
		DISCOVERY_SERVICE: Fetcher /* agenticgraph-mcp-staging */;
		ISSUANCE_SERVICE: Fetcher /* agenticgraph-travel-net-settlement-staging */;
		MARKETPLACE_SERVICE: Fetcher /* agenticgraph-marketplace-staging */;
		INFERENCE_OVERFLOW: Fetcher /* agenticgraph-travel-ollama-overflow-staging */;
	}
	interface ProductionEnv {
		BALANCE_CACHE: KVNamespace;
		PROVENANCE_ARCHIVE: R2Bucket;
		AI: Ai;
		DEPLOY_LANE: "Production_Lane";
		CASCADE_WALL_MS: "10000";
		SETTLEMENT_CURRENCY: "SGD";
		TRAVEL_GUARDRAIL_RETRY_BOUND: "3";
		TRAVEL_INTENT_MIN_BUDGET_MINOR: "1";
		TRAVEL_INTENT_MAX_BUDGET_MINOR: "9007199254740991";
		MODEL_CATALOG_JSON: "[{\"id\":\"@cf/openai/gpt-oss-20b\",\"provider_id\":\"@cf/openai/gpt-oss-20b\",\"license\":\"Apache-2.0\",\"path\":\"workers-ai-free\",\"free_daily_neuron_limit\":10000},{\"id\":\"@cf/openai/gpt-oss-20b-free-overflow\",\"provider_id\":\"@cf/openai/gpt-oss-20b\",\"license\":\"Apache-2.0\",\"path\":\"workers-ai-free-overflow\",\"free_daily_neuron_limit\":10000}]";
		PERMITTED_MODEL_LICENSES_JSON: "[\"Apache-2.0\",\"MIT\"]";
		COMMERCE_PROVIDER_SOURCE_REVISION: "0000000000000000000000000000000000000000";
		COMMERCE_PROVIDER_STORAGE_REVISION: "commerce-checkout-do-sqlite-v1";
		COMMERCE_PROVIDER_VERSION_ID: "production-unreleased";
		TRAVEL_COMMERCE_API_TOKEN: string;
		RECONCILIATION_OPERATOR_TOKEN: string;
		INFERENCE_OVERFLOW_TOKEN: string;
		CHECKOUT_PROVIDER_AUTH_SECRET: string;
		MARKETPLACE_PROVIDER_AUTH_SECRET: string;
		BUNDLE_GRAPH: DurableObjectNamespace<import("./src/index").BundleGraphStore>;
		ENVELOPE_LEDGER: DurableObjectNamespace<import("./src/index").EnvelopeLedger>;
		CHECKOUT_PROVIDER_STORE: DurableObjectNamespace<import("./src/index").CommerceCheckoutStore>;
		DISCOVERY_SERVICE: Fetcher /* agenticgraph-mcp */;
		ISSUANCE_SERVICE: Fetcher /* agenticgraph-travel-net-settlement-production */;
		MARKETPLACE_SERVICE: Fetcher /* agenticgraph-marketplace-production */;
		INFERENCE_OVERFLOW: Fetcher /* agenticgraph-travel-ollama-overflow */;
	}
	interface Env extends __BaseEnv_TravelCommerceEnv {}
}
interface TravelCommerceEnv extends __BaseEnv_TravelCommerceEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOY_LANE" | "CASCADE_WALL_MS" | "SETTLEMENT_CURRENCY" | "TRAVEL_GUARDRAIL_RETRY_BOUND" | "TRAVEL_INTENT_MIN_BUDGET_MINOR" | "TRAVEL_INTENT_MAX_BUDGET_MINOR" | "MODEL_CATALOG_JSON" | "PERMITTED_MODEL_LICENSES_JSON" | "COMMERCE_PROVIDER_SOURCE_REVISION" | "COMMERCE_PROVIDER_STORAGE_REVISION" | "COMMERCE_PROVIDER_VERSION_ID" | "TRAVEL_COMMERCE_API_TOKEN" | "RECONCILIATION_OPERATOR_TOKEN" | "INFERENCE_OVERFLOW_TOKEN" | "CHECKOUT_PROVIDER_AUTH_SECRET" | "MARKETPLACE_PROVIDER_AUTH_SECRET">> {}
}
