/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/agentic-graph-mcp/wrangler.toml --include-runtime=false cloudflare/workers/agentic-graph-mcp/worker-configuration.d.ts` (hash: aec4aff42efaf9f506c5e54d9dc5c5a5)
interface __BaseEnv_Env {
	TRAVEL_AGENT_DEFINITION_CACHE: KVNamespace;
	AI: Ai;
	AGENTIC_OS_MCP_PUBLIC_BASE_URL: "https://agentic-mcp-staging.huijoohwee.workers.dev" | "https://agentic-mcp-dev.huijoohwee.workers.dev" | "https://airvio.co";
	AGENTIC_OS_MCP_TOOL_LIST_NAME: "agentic-video-remix-staging" | "agentic-video-remix-dev" | "agentic-video-remix";
	AGENTIC_OS_LIVE_CLIENTS: "0";
	TRAVEL_AGENT_DEFINITIONS_JSON: "[{\"agentId\":\"agent-flight\",\"declaredCategory\":\"flight\"},{\"agentId\":\"agent-experience\",\"declaredCategory\":\"experience\"}]" | "[{\"agentId\":\"agent-flight\",\"declaredCategory\":\"flight\"},{\"agentId\":\"agent-hotel\",\"declaredCategory\":\"hotel\"},{\"agentId\":\"agent-experience\",\"declaredCategory\":\"experience\"}]";
	TRAVEL_DISCOVERY_MODE: "live" | "deterministic-demo";
	TRAVEL_DISCOVERY_DEADLINE_MS: "6000";
	TRAVEL_SETTLEMENT_CURRENCY: "SGD";
	COMMERCE_PROVIDER_SOURCE_REVISION: "0000000000000000000000000000000000000000";
	COMMERCE_PROVIDER_STORAGE_REVISION: "commerce-discovery-mcp-v1";
	COMMERCE_PROVIDER_VERSION_ID: "staging-unreleased" | "dev-unreleased" | "production-unreleased";
	AGENTIC_OS_AGENT_RUNTIME_BEARER_TOKEN: string;
	MCP_AGENT: DurableObjectNamespace<import("./index").AgenticGraphMcpAgent>;
	RUN_MANIFEST_STORE: DurableObjectNamespace<import("./index").RunManifestStore>;
	TRAVEL_DISCOVERY_HARNESS: Fetcher /* agentic-travel-discovery-staging */ | Fetcher /* agentic-travel-discovery */;
	TRAVEL_EXPERIENCE_DISCOVERY_HARNESS?: Fetcher /* agentic-travel-experience-discovery-staging */ | Fetcher /* agentic-travel-experience-discovery-production */;
	TRAVEL_GUARDRAIL: Service /* entrypoint TravelAgencyGuardrailService from agentic-travel-commerce-staging */ | Service /* entrypoint TravelAgencyGuardrailService from agentic-travel-commerce */ | Service /* entrypoint TravelAgencyGuardrailService from agentic-travel-commerce-production */;
	TRAVEL_DEMO_QUOTE_RULES_JSON?: "{\"flight\":{\"deltaMinor\":50},\"hotel\":{\"deltaMinor\":25},\"experience\":{\"deltaMinor\":10}}";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "AgenticGraphMcpAgent" | "RunManifestStore";
	}
	interface StagingEnv {
		TRAVEL_AGENT_DEFINITION_CACHE: KVNamespace;
		AI: Ai;
		AGENTIC_OS_MCP_PUBLIC_BASE_URL: "https://agentic-mcp-staging.huijoohwee.workers.dev";
		AGENTIC_OS_MCP_TOOL_LIST_NAME: "agentic-video-remix-staging";
		AGENTIC_OS_LIVE_CLIENTS: "0";
		TRAVEL_AGENT_DEFINITIONS_JSON: "[{\"agentId\":\"agent-flight\",\"declaredCategory\":\"flight\"},{\"agentId\":\"agent-experience\",\"declaredCategory\":\"experience\"}]";
		TRAVEL_DISCOVERY_MODE: "live";
		TRAVEL_DISCOVERY_DEADLINE_MS: "6000";
		TRAVEL_SETTLEMENT_CURRENCY: "SGD";
		COMMERCE_PROVIDER_SOURCE_REVISION: "0000000000000000000000000000000000000000";
		COMMERCE_PROVIDER_STORAGE_REVISION: "commerce-discovery-mcp-v1";
		COMMERCE_PROVIDER_VERSION_ID: "staging-unreleased";
		AGENTIC_OS_AGENT_RUNTIME_BEARER_TOKEN: string;
		MCP_AGENT: DurableObjectNamespace<import("./index").AgenticGraphMcpAgent>;
		RUN_MANIFEST_STORE: DurableObjectNamespace<import("./index").RunManifestStore>;
		TRAVEL_DISCOVERY_HARNESS: Fetcher /* agentic-travel-discovery-staging */;
		TRAVEL_EXPERIENCE_DISCOVERY_HARNESS: Fetcher /* agentic-travel-experience-discovery-staging */;
		TRAVEL_GUARDRAIL: Service /* entrypoint TravelAgencyGuardrailService from agentic-travel-commerce-staging */;
	}
	interface DevEnv {
		TRAVEL_AGENT_DEFINITION_CACHE: KVNamespace;
		AI: Ai;
		AGENTIC_OS_MCP_PUBLIC_BASE_URL: "https://agentic-mcp-dev.huijoohwee.workers.dev";
		AGENTIC_OS_MCP_TOOL_LIST_NAME: "agentic-video-remix-dev";
		AGENTIC_OS_LIVE_CLIENTS: "0";
		TRAVEL_AGENT_DEFINITIONS_JSON: "[{\"agentId\":\"agent-flight\",\"declaredCategory\":\"flight\"},{\"agentId\":\"agent-hotel\",\"declaredCategory\":\"hotel\"},{\"agentId\":\"agent-experience\",\"declaredCategory\":\"experience\"}]";
		TRAVEL_DISCOVERY_MODE: "deterministic-demo";
		TRAVEL_DISCOVERY_DEADLINE_MS: "6000";
		TRAVEL_SETTLEMENT_CURRENCY: "SGD";
		COMMERCE_PROVIDER_SOURCE_REVISION: "0000000000000000000000000000000000000000";
		COMMERCE_PROVIDER_STORAGE_REVISION: "commerce-discovery-mcp-v1";
		COMMERCE_PROVIDER_VERSION_ID: "dev-unreleased";
		TRAVEL_DEMO_QUOTE_RULES_JSON: "{\"flight\":{\"deltaMinor\":50},\"hotel\":{\"deltaMinor\":25},\"experience\":{\"deltaMinor\":10}}";
		AGENTIC_OS_AGENT_RUNTIME_BEARER_TOKEN: string;
		MCP_AGENT: DurableObjectNamespace<import("./index").AgenticGraphMcpAgent>;
		RUN_MANIFEST_STORE: DurableObjectNamespace<import("./index").RunManifestStore>;
		TRAVEL_DISCOVERY_HARNESS: Fetcher /* agentic-travel-discovery-staging */;
		TRAVEL_GUARDRAIL: Service /* entrypoint TravelAgencyGuardrailService from agentic-travel-commerce */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AGENTIC_OS_MCP_PUBLIC_BASE_URL" | "AGENTIC_OS_MCP_TOOL_LIST_NAME" | "AGENTIC_OS_LIVE_CLIENTS" | "TRAVEL_AGENT_DEFINITIONS_JSON" | "TRAVEL_DISCOVERY_MODE" | "TRAVEL_DISCOVERY_DEADLINE_MS" | "TRAVEL_SETTLEMENT_CURRENCY" | "COMMERCE_PROVIDER_SOURCE_REVISION" | "COMMERCE_PROVIDER_STORAGE_REVISION" | "COMMERCE_PROVIDER_VERSION_ID" | "AGENTIC_OS_AGENT_RUNTIME_BEARER_TOKEN" | "TRAVEL_DEMO_QUOTE_RULES_JSON">> {}
}
