/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/agentic-graph-marketplace/wrangler.jsonc --include-runtime=false --env-interface=MarketplaceEnv cloudflare/workers/agentic-graph-marketplace/worker-configuration.d.ts` (hash: a42522768dc6124f840b1e1e32d2c30f)
interface __BaseEnv_MarketplaceEnv {
	MARKETPLACE_DB: D1Database;
	COMMERCE_PROVIDER_SOURCE_REVISION: "0000000000000000000000000000000000000000";
	COMMERCE_PROVIDER_STORAGE_REVISION: "marketplace-d1-0017";
	COMMERCE_PROVIDER_VERSION_ID: "";
	MARKETPLACE_PROVIDER_AUTH_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {
		MARKETPLACE_DB: D1Database;
		COMMERCE_PROVIDER_SOURCE_REVISION: "0000000000000000000000000000000000000000";
		COMMERCE_PROVIDER_STORAGE_REVISION: "marketplace-d1-0017";
		COMMERCE_PROVIDER_VERSION_ID: "";
		MARKETPLACE_PROVIDER_AUTH_SECRET: string;
	}
	interface ProductionEnv {
		MARKETPLACE_DB: D1Database;
		COMMERCE_PROVIDER_SOURCE_REVISION: "0000000000000000000000000000000000000000";
		COMMERCE_PROVIDER_STORAGE_REVISION: "marketplace-d1-0017";
		COMMERCE_PROVIDER_VERSION_ID: "";
		MARKETPLACE_PROVIDER_AUTH_SECRET: string;
	}
	interface Env extends __BaseEnv_MarketplaceEnv {}
}
interface MarketplaceEnv extends __BaseEnv_MarketplaceEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "COMMERCE_PROVIDER_SOURCE_REVISION" | "COMMERCE_PROVIDER_STORAGE_REVISION" | "COMMERCE_PROVIDER_VERSION_ID" | "MARKETPLACE_PROVIDER_AUTH_SECRET">> {}
}
