/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/agentic-graph-travel-operator-gateway/wrangler.jsonc --include-runtime=false --env-interface=TravelOperatorGatewayEnv cloudflare/workers/agentic-graph-travel-operator-gateway/worker-configuration.d.ts` (hash: d52b16d1b8c07210f2a30a136c7a7561)
interface __BaseEnv_TravelOperatorGatewayEnv {
	DEPLOY_LANE: "Staging_Lane" | "Production_Lane" | "Dev_Lane";
	ACCESS_ISSUER: "https://replace-with-staging-team.cloudflareaccess.com" | "https://replace-with-production-team.cloudflareaccess.com" | "https://replace-with-dev-team.cloudflareaccess.com";
	ACCESS_AUDIENCE: "replace-with-staging-access-audience" | "replace-with-production-access-audience" | "replace-with-dev-access-audience";
	ACCESS_JWKS_TIMEOUT_MS: "3000";
	ACCESS_JWKS_CACHE_TTL_MS: "300000";
	TRAVEL_CONTROL_TIMEOUT_MS: "5000";
	TRAVEL_COMMERCE_CONTROL: Fetcher /* agentic-travel-commerce-staging */ | Fetcher /* agentic-travel-commerce-production */ | Fetcher /* agentic-travel-commerce */;
}
declare namespace Cloudflare {
	interface StagingEnv {
		DEPLOY_LANE: "Staging_Lane";
		ACCESS_ISSUER: "https://replace-with-staging-team.cloudflareaccess.com";
		ACCESS_AUDIENCE: "replace-with-staging-access-audience";
		ACCESS_JWKS_TIMEOUT_MS: "3000";
		ACCESS_JWKS_CACHE_TTL_MS: "300000";
		TRAVEL_CONTROL_TIMEOUT_MS: "5000";
		TRAVEL_COMMERCE_CONTROL: Fetcher /* agentic-travel-commerce-staging */;
	}
	interface ProductionEnv {
		DEPLOY_LANE: "Production_Lane";
		ACCESS_ISSUER: "https://replace-with-production-team.cloudflareaccess.com";
		ACCESS_AUDIENCE: "replace-with-production-access-audience";
		ACCESS_JWKS_TIMEOUT_MS: "3000";
		ACCESS_JWKS_CACHE_TTL_MS: "300000";
		TRAVEL_CONTROL_TIMEOUT_MS: "5000";
		TRAVEL_COMMERCE_CONTROL: Fetcher /* agentic-travel-commerce-production */;
	}
	interface Env extends __BaseEnv_TravelOperatorGatewayEnv {}
}
interface TravelOperatorGatewayEnv extends __BaseEnv_TravelOperatorGatewayEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "DEPLOY_LANE" | "ACCESS_ISSUER" | "ACCESS_AUDIENCE" | "ACCESS_JWKS_TIMEOUT_MS" | "ACCESS_JWKS_CACHE_TTL_MS" | "TRAVEL_CONTROL_TIMEOUT_MS">> {}
}
