/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=cloudflare/workers/agenticgraph-mcp/wrangler.toml --include-runtime=false cloudflare/workers/agenticgraph-mcp/worker-configuration.d.ts` (hash: 1e8af29ee387aefa07361b8723581506)
interface __BaseEnv_Env {
	TRAVEL_AGENT_DEFINITION_CACHE: KVNamespace;
	AI: Ai;
	AGENTICGRAPH_MCP_PUBLIC_BASE_URL: "https://agenticgraph-mcp-staging.huijoohwee.workers.dev" | "https://agenticgraph-mcp-dev.huijoohwee.workers.dev" | "https://airvio.co";
	AGENTICGRAPH_MCP_TOOL_LIST_NAME: "agenticgraph-video-remix-staging" | "agenticgraph-video-remix-dev" | "agenticgraph-video-remix";
	AGENTICGRAPH_LIVE_CLIENTS: "0";
	TRAVEL_AGENT_DEFINITIONS_JSON: "[{\"agentId\":\"agent-flight\",\"declaredCategory\":\"flight\"},{\"agentId\":\"agent-experience\",\"declaredCategory\":\"experience\"}]" | "[{\"agentId\":\"agent-flight\",\"declaredCategory\":\"flight\"},{\"agentId\":\"agent-hotel\",\"declaredCategory\":\"hotel\"},{\"agentId\":\"agent-experience\",\"declaredCategory\":\"experience\"}]";
	TRAVEL_DISCOVERY_MODE: "live" | "deterministic-demo";
	TRAVEL_DISCOVERY_DEADLINE_MS: "6000";
	TRAVEL_SETTLEMENT_CURRENCY: "SGD";
	AGENTICGRAPH_AGENT_RUNTIME_BEARER_TOKEN: string;
	MCP_AGENT: DurableObjectNamespace<import("./index").AgenticGraphMcpAgent>;
	RUN_MANIFEST_STORE: DurableObjectNamespace<import("./index").RunManifestStore>;
	TRAVEL_DISCOVERY_HARNESS: Fetcher /* agenticgraph-travel-discovery-staging */ | Fetcher /* agenticgraph-travel-discovery */;
	TRAVEL_EXPERIENCE_DISCOVERY_HARNESS?: Fetcher /* agenticgraph-travel-experience-discovery-staging */ | Fetcher /* agenticgraph-travel-experience-discovery-production */;
	TRAVEL_GUARDRAIL: Service /* entrypoint TravelAgencyGuardrailService from agenticgraph-travel-commerce-staging */ | Service /* entrypoint TravelAgencyGuardrailService from agenticgraph-travel-commerce */ | Service /* entrypoint TravelAgencyGuardrailService from agenticgraph-travel-commerce-production */;
	TRAVEL_DEMO_QUOTE_RULES_JSON?: "{\"flight\":{\"deltaMinor\":50},\"hotel\":{\"deltaMinor\":25},\"experience\":{\"deltaMinor\":10}}";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "AgenticGraphMcpAgent" | "RunManifestStore";
	}
	interface StagingEnv {
		TRAVEL_AGENT_DEFINITION_CACHE: KVNamespace;
		AI: Ai;
		AGENTICGRAPH_MCP_PUBLIC_BASE_URL: "https://agenticgraph-mcp-staging.huijoohwee.workers.dev";
		AGENTICGRAPH_MCP_TOOL_LIST_NAME: "agenticgraph-video-remix-staging";
		AGENTICGRAPH_LIVE_CLIENTS: "0";
		TRAVEL_AGENT_DEFINITIONS_JSON: "[{\"agentId\":\"agent-flight\",\"declaredCategory\":\"flight\"},{\"agentId\":\"agent-experience\",\"declaredCategory\":\"experience\"}]";
		TRAVEL_DISCOVERY_MODE: "live";
		TRAVEL_DISCOVERY_DEADLINE_MS: "6000";
		TRAVEL_SETTLEMENT_CURRENCY: "SGD";
		AGENTICGRAPH_AGENT_RUNTIME_BEARER_TOKEN: string;
		MCP_AGENT: DurableObjectNamespace<import("./index").AgenticGraphMcpAgent>;
		RUN_MANIFEST_STORE: DurableObjectNamespace<import("./index").RunManifestStore>;
		TRAVEL_DISCOVERY_HARNESS: Fetcher /* agenticgraph-travel-discovery-staging */;
		TRAVEL_EXPERIENCE_DISCOVERY_HARNESS: Fetcher /* agenticgraph-travel-experience-discovery-staging */;
		TRAVEL_GUARDRAIL: Service /* entrypoint TravelAgencyGuardrailService from agenticgraph-travel-commerce-staging */;
	}
	interface DevEnv {
		TRAVEL_AGENT_DEFINITION_CACHE: KVNamespace;
		AI: Ai;
		AGENTICGRAPH_MCP_PUBLIC_BASE_URL: "https://agenticgraph-mcp-dev.huijoohwee.workers.dev";
		AGENTICGRAPH_MCP_TOOL_LIST_NAME: "agenticgraph-video-remix-dev";
		AGENTICGRAPH_LIVE_CLIENTS: "0";
		TRAVEL_AGENT_DEFINITIONS_JSON: "[{\"agentId\":\"agent-flight\",\"declaredCategory\":\"flight\"},{\"agentId\":\"agent-hotel\",\"declaredCategory\":\"hotel\"},{\"agentId\":\"agent-experience\",\"declaredCategory\":\"experience\"}]";
		TRAVEL_DISCOVERY_MODE: "deterministic-demo";
		TRAVEL_DISCOVERY_DEADLINE_MS: "6000";
		TRAVEL_SETTLEMENT_CURRENCY: "SGD";
		TRAVEL_DEMO_QUOTE_RULES_JSON: "{\"flight\":{\"deltaMinor\":50},\"hotel\":{\"deltaMinor\":25},\"experience\":{\"deltaMinor\":10}}";
		AGENTICGRAPH_AGENT_RUNTIME_BEARER_TOKEN: string;
		MCP_AGENT: DurableObjectNamespace<import("./index").AgenticGraphMcpAgent>;
		RUN_MANIFEST_STORE: DurableObjectNamespace<import("./index").RunManifestStore>;
		TRAVEL_DISCOVERY_HARNESS: Fetcher /* agenticgraph-travel-discovery-staging */;
		TRAVEL_GUARDRAIL: Service /* entrypoint TravelAgencyGuardrailService from agenticgraph-travel-commerce */;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AGENTICGRAPH_MCP_PUBLIC_BASE_URL" | "AGENTICGRAPH_MCP_TOOL_LIST_NAME" | "AGENTICGRAPH_LIVE_CLIENTS" | "TRAVEL_AGENT_DEFINITIONS_JSON" | "TRAVEL_DISCOVERY_MODE" | "TRAVEL_DISCOVERY_DEADLINE_MS" | "TRAVEL_SETTLEMENT_CURRENCY" | "AGENTICGRAPH_AGENT_RUNTIME_BEARER_TOKEN" | "TRAVEL_DEMO_QUOTE_RULES_JSON">> {}
}
